### ISSUE TITLE
LanguageServer always crashes on start.

### ISSUE THREAD

**Issue by nojvek** [RLovelett/langserver-swift#25] opened 2017-07-10 21:11 UTC
```
fatal error: 'try!' expression unexpectedly raised an error: PackageModel.Package.Error.noManifest(baseURL: "/Users/nojvek/git/Swiftris", version: nil): file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-802.0.53/src/swift/stdlib/public/core/ErrorType.swift, line 182
Current stack trace:
0    libswiftCore.dylib                 0x00000001027b2130 swift_reportError + 129
1    libswiftCore.dylib                 0x00000001027cea40 _swift_stdlib_reportFatalErrorInFile + 100
2    libswiftCore.dylib                 0x00000001025bfba0 (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 124
3    libswiftCore.dylib                 0x0000000102776360 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 93
4    libswiftCore.dylib                 0x00000001025bf250 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
5    libswiftCore.dylib                 0x0000000102778880 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1) + 144
6    libswiftCore.dylib                 0x00000001025bf760 specialized specialized String._withUnsafeBufferPointerToUTF8<A> ((UnsafeBufferPointer<UInt8>) throws -> A) throws -> A + 127
7    libswiftCore.dylib                 0x0000000102739f40 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1) + 185
8    libswiftCore.dylib                 0x00000001025bf250 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
9    libswiftCore.dylib                 0x00000001026f0130 specialized _assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never + 144
10   libswiftCore.dylib                 0x00000001025e8130 swift_unexpectedError_merged + 289
11   LanguageServer                     0x00000001020df250 Server.init(inDirectory : AbsolutePath) -> Server + 4615
12   LanguageServer                     0x00000001020ded90 Server.init(InitializeParams) -> Server? + 581
13   LanguageServer                     0x00000001020df140 Server.__allocating_init(InitializeParams) -> Server? + 46
14   LanguageServer                     0x0000000101d1a3c0 handle(Request) -> Response + 1221
15   LanguageServer                     0x0000000101d184e0 (closure #1) + 1070
16   LanguageServer                     0x0000000101d19300 thunk + 73
17   Foundation                         0x00007fffa2a22ace -[__NSObserver _doit:] + 304
18   CoreFoundation                     0x00007fffa0ff8450 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
19   CoreFoundation                     0x00007fffa0ff81b0 _CFXRegistrationPost + 427
20   CoreFoundation                     0x00007fffa0ff8090 ___CFXNotificationPost_block_invoke + 50
21   CoreFoundation                     0x00007fffa0fb4e00 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1827
22   CoreFoundation                     0x00007fffa0fb4300 _CFXNotificationPost + 604
23   Foundation                         0x00007fffa29d98c5 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
24   Foundation                         0x00007fffa2a969ac _performFileHandleSource + 1144
25   CoreFoundation                     0x00007fffa1002310 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
26   CoreFoundation                     0x00007fffa0fe2ff0 __CFRunLoopDoSources0 + 557
27   CoreFoundation                     0x00007fffa0fe2370 __CFRunLoopRun + 934
28   CoreFoundation                     0x00007fffa0fe1f70 CFRunLoopRunSpecific + 420
29   Foundation                         0x00007fffa29f53cd -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 277
30   Foundation                         0x00007fffa29f536e -[NSRunLoop(NSRunLoop) run] + 76
31   LanguageServer                     0x0000000101d17f20 main + 915
32   libdyld.dylib                      0x00007fffb675c234 start + 1
[Info  - 2:09:33 PM] Connection to server got closed. Server will restart.
fatal error: 'try!' expression unexpectedly raised an error: PackageModel.Package.Error.noManifest(baseURL: "/Users/nojvek/git/Swiftris", version: nil): file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-802.0.53/src/swift/stdlib/public/core/ErrorType.swift, line 182
Current stack trace:
0    libswiftCore.dylib                 0x000000010b7a0130 swift_reportError + 129
1    libswiftCore.dylib                 0x000000010b7bca40 _swift_stdlib_reportFatalErrorInFile + 100
2    libswiftCore.dylib                 0x000000010b5adba0 (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 124
3    libswiftCore.dylib                 0x000000010b764360 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 93
4    libswiftCore.dylib                 0x000000010b5ad250 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
5    libswiftCore.dylib                 0x000000010b766880 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1) + 144
6    libswiftCore.dylib                 0x000000010b5ad760 specialized specialized String._withUnsafeBufferPointerToUTF8<A> ((UnsafeBufferPointer<UInt8>) throws -> A) throws -> A + 127
7    libswiftCore.dylib                 0x000000010b727f40 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1) + 185
8    libswiftCore.dylib                 0x000000010b5ad250 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
9    libswiftCore.dylib                 0x000000010b6de130 specialized _assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never + 144
10   libswiftCore.dylib                 0x000000010b5d6130 swift_unexpectedError_merged + 289
11   LanguageServer                     0x000000010b0cf250 Server.init(inDirectory : AbsolutePath) -> Server + 4615
12   LanguageServer                     0x000000010b0ced90 Server.init(InitializeParams) -> Server? + 581
13   LanguageServer                     0x000000010b0cf140 Server.__allocating_init(InitializeParams) -> Server? + 46
14   LanguageServer                     0x000000010ad0a3c0 handle(Request) -> Response + 1221
15   LanguageServer                     0x000000010ad084e0 (closure #1) + 1070
16   LanguageServer                     0x000000010ad09300 thunk + 73
17   Foundation                         0x00007fffa2a22ace -[__NSObserver _doit:] + 304
18   CoreFoundation                     0x00007fffa0ff8450 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
19   CoreFoundation                     0x00007fffa0ff81b0 _CFXRegistrationPost + 427
20   CoreFoundation                     0x00007fffa0ff8090 ___CFXNotificationPost_block_invoke + 50
21   CoreFoundation                     0x00007fffa0fb4e00 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1827
22   CoreFoundation                     0x00007fffa0fb4300 _CFXNotificationPost + 604
23   Foundation                         0x00007fffa29d98c5 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
24   Foundation                         0x00007fffa2a969ac _performFileHandleSource + 1144
25   CoreFoundation                     0x00007fffa1002310 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
26   CoreFoundation                     0x00007fffa0fe2ff0 __CFRunLoopDoSources0 + 557
27   CoreFoundation                     0x00007fffa0fe2370 __CFRunLoopRun + 934
28   CoreFoundation                     0x00007fffa0fe1f70 CFRunLoopRunSpecific + 420
29   Foundation                         0x00007fffa29f53cd -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 277
30   Foundation                         0x00007fffa29f536e -[NSRunLoop(NSRunLoop) run] + 76
31   LanguageServer                     0x000000010ad07f20 main + 915
32   libdyld.dylib                      0x00007fffb675c234 start + 1
[Info  - 2:09:33 PM] Connection to server got closed. Server will restart.
fatal error: 'try!' expression unexpectedly raised an error: PackageModel.Package.Error.noManifest(baseURL: "/Users/nojvek/git/Swiftris", version: nil): file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-802.0.53/src/swift/stdlib/public/core/ErrorType.swift, line 182
Current stack trace:
0    libswiftCore.dylib                 0x000000010397f130 swift_reportError + 129
1    libswiftCore.dylib                 0x000000010399ba40 _swift_stdlib_reportFatalErrorInFile + 100
2    libswiftCore.dylib                 0x000000010378cba0 (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 124
3    libswiftCore.dylib                 0x0000000103943360 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 93
4    libswiftCore.dylib                 0x000000010378c250 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
5    libswiftCore.dylib                 0x0000000103945880 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1) + 144
6    libswiftCore.dylib                 0x000000010378c760 specialized specialized String._withUnsafeBufferPointerToUTF8<A> ((UnsafeBufferPointer<UInt8>) throws -> A) throws -> A + 127
7    libswiftCore.dylib                 0x0000000103906f40 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1) + 185
8    libswiftCore.dylib                 0x000000010378c250 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
9    libswiftCore.dylib                 0x00000001038bd130 specialized _assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never + 144
10   libswiftCore.dylib                 0x00000001037b5130 swift_unexpectedError_merged + 289
11   LanguageServer                     0x00000001032ac250 Server.init(inDirectory : AbsolutePath) -> Server + 4615
12   LanguageServer                     0x00000001032abd90 Server.init(InitializeParams) -> Server? + 581
13   LanguageServer                     0x00000001032ac140 Server.__allocating_init(InitializeParams) -> Server? + 46
14   LanguageServer                     0x0000000102ee73c0 handle(Request) -> Response + 1221
15   LanguageServer                     0x0000000102ee54e0 (closure #1) + 1070
16   LanguageServer                     0x0000000102ee6300 thunk + 73
17   Foundation                         0x00007fffa2a22ace -[__NSObserver _doit:] + 304
18   CoreFoundation                     0x00007fffa0ff8450 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
19   CoreFoundation                     0x00007fffa0ff81b0 _CFXRegistrationPost + 427
20   CoreFoundation                     0x00007fffa0ff8090 ___CFXNotificationPost_block_invoke + 50
21   CoreFoundation                     0x00007fffa0fb4e00 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1827
22   CoreFoundation                     0x00007fffa0fb4300 _CFXNotificationPost + 604
23   Foundation                         0x00007fffa29d98c5 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
24   Foundation                         0x00007fffa2a969ac _performFileHandleSource + 1144
25   CoreFoundation                     0x00007fffa1002310 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
26   CoreFoundation                     0x00007fffa0fe2ff0 __CFRunLoopDoSources0 + 557
27   CoreFoundation                     0x00007fffa0fe2370 __CFRunLoopRun + 934
28   CoreFoundation                     0x00007fffa0fe1f70 CFRunLoopRunSpecific + 420
29   Foundation                         0x00007fffa29f53cd -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 277
30   Foundation                         0x00007fffa29f536e -[NSRunLoop(NSRunLoop) run] + 76
31   LanguageServer                     0x0000000102ee4f20 main + 915
32   libdyld.dylib                      0x00007fffb675c234 start + 1
[Info  - 2:09:33 PM] Connection to server got closed. Server will restart.
fatal error: 'try!' expression unexpectedly raised an error: PackageModel.Package.Error.noManifest(baseURL: "/Users/nojvek/git/Swiftris", version: nil): file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-802.0.53/src/swift/stdlib/public/core/ErrorType.swift, line 182
Current stack trace:
0    libswiftCore.dylib                 0x0000000106a46130 swift_reportError + 129
1    libswiftCore.dylib                 0x0000000106a62a40 _swift_stdlib_reportFatalErrorInFile + 100
2    libswiftCore.dylib                 0x0000000106853ba0 (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 124
3    libswiftCore.dylib                 0x0000000106a0a360 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 93
4    libswiftCore.dylib                 0x0000000106853250 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
5    libswiftCore.dylib                 0x0000000106a0c880 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1) + 144
6    libswiftCore.dylib                 0x0000000106853760 specialized specialized String._withUnsafeBufferPointerToUTF8<A> ((UnsafeBufferPointer<UInt8>) throws -> A) throws -> A + 127
7    libswiftCore.dylib                 0x00000001069cdf40 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1) + 185
8    libswiftCore.dylib                 0x0000000106853250 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
9    libswiftCore.dylib                 0x0000000106984130 specialized _assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never + 144
10   libswiftCore.dylib                 0x000000010687c130 swift_unexpectedError_merged + 289
11   LanguageServer                     0x0000000106375250 Server.init(inDirectory : AbsolutePath) -> Server + 4615
12   LanguageServer                     0x0000000106374d90 Server.init(InitializeParams) -> Server? + 581
13   LanguageServer                     0x0000000106375140 Server.__allocating_init(InitializeParams) -> Server? + 46
14   LanguageServer                     0x0000000105fb03c0 handle(Request) -> Response + 1221
15   LanguageServer                     0x0000000105fae4e0 (closure #1) + 1070
16   LanguageServer                     0x0000000105faf300 thunk + 73
17   Foundation                         0x00007fffa2a22ace -[__NSObserver _doit:] + 304
18   CoreFoundation                     0x00007fffa0ff8450 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
19   CoreFoundation                     0x00007fffa0ff81b0 _CFXRegistrationPost + 427
20   CoreFoundation                     0x00007fffa0ff8090 ___CFXNotificationPost_block_invoke + 50
21   CoreFoundation                     0x00007fffa0fb4e00 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1827
22   CoreFoundation                     0x00007fffa0fb4300 _CFXNotificationPost + 604
23   Foundation                         0x00007fffa29d98c5 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
24   Foundation                         0x00007fffa2a969ac _performFileHandleSource + 1144
25   CoreFoundation                     0x00007fffa1002310 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
26   CoreFoundation                     0x00007fffa0fe2ff0 __CFRunLoopDoSources0 + 557
27   CoreFoundation                     0x00007fffa0fe2370 __CFRunLoopRun + 934
28   CoreFoundation                     0x00007fffa0fe1f70 CFRunLoopRunSpecific + 420
29   Foundation                         0x00007fffa29f53cd -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 277
30   Foundation                         0x00007fffa29f536e -[NSRunLoop(NSRunLoop) run] + 76
31   LanguageServer                     0x0000000105fadf20 main + 915
32   libdyld.dylib                      0x00007fffb675c234 start + 1
[Info  - 2:09:33 PM] Connection to server got closed. Server will restart.
fatal error: 'try!' expression unexpectedly raised an error: PackageModel.Package.Error.noManifest(baseURL: "/Users/nojvek/git/Swiftris", version: nil): file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-802.0.53/src/swift/stdlib/public/core/ErrorType.swift, line 182
Current stack trace:
0    libswiftCore.dylib                 0x00000001012b8130 swift_reportError + 129
1    libswiftCore.dylib                 0x00000001012d4a40 _swift_stdlib_reportFatalErrorInFile + 100
2    libswiftCore.dylib                 0x00000001010c5ba0 (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 124
3    libswiftCore.dylib                 0x000000010127c360 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 93
4    libswiftCore.dylib                 0x00000001010c5250 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
5    libswiftCore.dylib                 0x000000010127e880 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1).(closure #1) + 144
6    libswiftCore.dylib                 0x00000001010c5760 specialized specialized String._withUnsafeBufferPointerToUTF8<A> ((UnsafeBufferPointer<UInt8>) throws -> A) throws -> A + 127
7    libswiftCore.dylib                 0x000000010123ff40 partial apply for (_assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never).(closure #1) + 185
8    libswiftCore.dylib                 0x00000001010c5250 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 342
9    libswiftCore.dylib                 0x00000001011f6130 specialized _assertionFailure(StaticString, String, file : StaticString, line : UInt, flags : UInt32) -> Never + 144
10   libswiftCore.dylib                 0x00000001010ee130 swift_unexpectedError_merged + 289
11   LanguageServer                     0x0000000100be1250 Server.init(inDirectory : AbsolutePath) -> Server + 4615
12   LanguageServer                     0x0000000100be0d90 Server.init(InitializeParams) -> Server? + 581
13   LanguageServer                     0x0000000100be1140 Server.__allocating_init(InitializeParams) -> Server? + 46
14   LanguageServer                     0x000000010081c3c0 handle(Request) -> Response + 1221
15   LanguageServer                     0x000000010081a4e0 (closure #1) + 1070
16   LanguageServer                     0x000000010081b300 thunk + 73
17   Foundation                         0x00007fffa2a22ace -[__NSObserver _doit:] + 304
18   CoreFoundation                     0x00007fffa0ff8450 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
19   CoreFoundation                     0x00007fffa0ff81b0 _CFXRegistrationPost + 427
20   CoreFoundation                     0x00007fffa0ff8090 ___CFXNotificationPost_block_invoke + 50
21   CoreFoundation                     0x00007fffa0fb4e00 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1827
22   CoreFoundation                     0x00007fffa0fb4300 _CFXNotificationPost + 604
23   Foundation                         0x00007fffa29d98c5 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
24   Foundation                         0x00007fffa2a969ac _performFileHandleSource + 1144
25   CoreFoundation                     0x00007fffa1002310 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
26   CoreFoundation                     0x00007fffa0fe2ff0 __CFRunLoopDoSources0 + 557
27   CoreFoundation                     0x00007fffa0fe2370 __CFRunLoopRun + 934
28   CoreFoundation                     0x00007fffa0fe1f70 CFRunLoopRunSpecific + 420
29   Foundation                         0x00007fffa29f53cd -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 277
30   Foundation                         0x00007fffa29f536e -[NSRunLoop(NSRunLoop) run] + 76
31   LanguageServer                     0x0000000100819f20 main + 915
32   libdyld.dylib                      0x00007fffb675c234 start + 1
[Error - 2:09:33 PM] Connection to server got closed. Server will not be restarted.

```

**Comment by mklbtz** [comment] 2017-09-20 03:56
Duplicate of #22

**Closed** 2018-05-29 02:43 UTC
Labels: duplicate
